name: ci

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  BOT_USER: "Deployment Bot"
  BOT_EMAIL: "verible-dev@googlegroups.com"

jobs:


  WindowsBuild:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create Cache Timestamp
      id: cache_timestamp
      uses: nanzm/get-time-action@v1.1
      with:
        format: 'YYYY-MM-DD-HH-mm-ss'

    - name: Mount bazel cache
      uses: actions/cache@v2
      # Currently, this is using >3GiB, bringing us well beyond 5GiB per repo
      if: false
      with:
        path: "c:/users/runneradmin/_bazel_runneradmin"
        key: bazelcache_windows2_${{ steps.cache_timestamp.outputs.time }}
        restore-keys: bazelcache_windows2_

    - name: Install dependencies
      run: choco install llvm

    - name: Debug bazel directory settings
      run: bazel info

    - name: Run Tests
      run: bazel test --test_output=errors //...

    - name: Build Verible Binaries
      run: bazel build -c opt :install-binaries

    - name: Install Verible & Zip
      run: |
        bazel run -c opt :install -- verible-win64-${GITHUB_SHA}
        7z a verible-win64-${GITHUB_SHA}.zip verible-win64-${GITHUB_SHA}

     - name: 📤 Upload artifact
       uses: actions/upload-artifact@v2
       with:
         path: verible-win64-${GITHUB_SHA}.zip


    # We need to shut down bazel to let go of the filedescriptors in the
    # cache directory. Because of strange filesystem semantics on Windows, this
    # prevents packaging up the cache.
    - name: Stop Bazel
      run: |
        bazel shutdown
        # The cache pack/restore has issues with these symbolic links
        rm c:/users/runneradmin/_bazel_runneradmin/*/install
        rm c:/users/runneradmin/_bazel_runneradmin/*/java.log

  Release:
    needs: [ WindowsBuild ]
    runs-on: ubuntu-20.04
    name: 📦 Release
    if: ${{github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')}}

    steps:

    - uses: actions/checkout@v2
      with:
       # Download complete repository + tags
       fetch-depth: 0

    - name: 📥 Download artifacts
      uses: actions/download-artifact@v2

    - name: Generate and apply TAG
      run: |
        git config --local user.name "$BOT_USER"
        git config --local user.email "$BOT_EMAIL"

        # Create a tag of form v0.0-183-gdf2b162-20191112132344
        TAG="${TAG:-$(git describe --match=v*)}"

        git tag "$TAG" || true
        echo "TAG=$TAG" >> $GITHUB_ENV

        ls -lah artifact

    - name: Deploy release and assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: artifact/*.zip
        tag: ${{ env.TAG }}
        overwrite: true
        file_glob: true
